#line 2 "lex.yy.cc"

#line 4 "lex.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, (yytext_ptr), yyleng + 1 ); \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 17
#define YY_END_OF_BUFFER 18
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[240] =
    {   0,
        0,    0,   18,   16,    6,    1,   16,   16,   15,   16,
       14,   13,   17,   16,    7,   16,   16,   16,    0,    0,
        0,   16,   16,    2,    0,    0,   16,   16,    0,    0,
        8,   11,   10,   12,   16,   16,   16,   16,    0,    0,
        4,    2,    0,    0,    2,    2,    2,    2,    2,    0,
       16,   16,   16,   16,    0,    3,    0,   16,   16,   16,
        0,    0,    5,    9,    0,    0,    4,   16,   16,    2,
        0,    0,    4,    0,    0,    4,   16,    2,    2,    2,
        2,    2,    0,    2,    2,    2,    2,    0,    2,    0,
        3,    0,   16,   16,    2,    0,    3,    0,    0,    3,

        0,   16,    0,    0,    5,   16,   16,    2,    0,    0,
        5,    0,    0,    5,   16,    0,    4,    2,    0,    0,
        4,    2,    2,    2,    2,    2,    2,    0,    4,   16,
        0,    2,    2,    2,    2,    2,    2,    3,    0,    2,
        0,    3,    0,    2,    2,    2,    2,    2,    2,    3,
        0,   16,    0,    0,    5,    2,    0,    0,    5,    2,
        2,    2,    2,    2,    2,    0,    5,   16,    0,    2,
        2,    2,    2,    2,    2,    0,    4,    2,    2,    2,
        2,    2,    0,    2,    2,    2,    2,    2,    2,    2,
        3,    0,    2,    2,    2,    2,    2,    0,    2,    2,

        2,    2,    2,    2,    2,    0,    5,    2,    2,    2,
        2,    2,    0,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    5,    1,    6,    1,    7,
        8,    1,    1,    1,    1,    1,    1,    1,    1,    9,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   10,
        1,   11,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   12,    1,    1,    1,   13,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   14,   15,   16,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[17] =
    {   0,
        1,    2,    3,    1,    1,    4,    1,    1,    1,    4,
        4,    1,    1,    1,    4,    1
    } ;

static const flex_int16_t yy_base[283] =
    {   0,
        0,    0,  287,   16,  274,  269,   32,   42,   46,  269,
       55,   46,   65,   80,  270,    0,  263,    0,  262,    0,
       94,    0,  106,  121,  136,  146,  161,  177,  192,  255,
      259,  257,  256,  234,  235,    0,  199,  214,  229,   51,
        0,  242,   50,  235,    0,    0,  257,  267,  281,  292,
      233,    0,  299,  314,  329,    0,   53,    0,  336,  352,
      367,   58,    0,  230,   60,  232,  222,    0,  383,  399,
      414,   62,    0,  426,  438,  207,  199,    0,    0,   94,
      448,   95,  199,    0,  461,    0,    0,  197,    0,  103,
      185,  157,    0,  473,  489,  504,    0,  101,  515,  138,

      526,  138,  129,  117,  107,    0,  538,  554,  569,  141,
        0,  584,  599,  108,  104,   99, 1333,  611,  624,    0,
      634,    0,    0,  648,  660,    0,  671,  683,    0,  695,
      709,    0,  142,    0,    0,    0,  143, 1333,   98,  722,
      735,  744,    0,    0,    0,  758,    0,  769,  780,    0,
      791,  803,  817,   76, 1333,  829,  842,    0,    0,    0,
        0,  857,  872,    0,  883,  898,    0,  910,  924,    0,
        0,  939,  950,    0,  964,   75,  147,    0,  975,    0,
        0,    0,  986,    0,    0,    0,  998,    0, 1008, 1022,
      194,   63,    0,    0, 1032,    0,    0, 1042,    0,    0,

        0, 1053, 1067,    0, 1082,   48,  195,    0, 1096,    0,
        0,    0, 1110,    0,    0, 1124,  196,    0,    0,    0,
        0,    0,  260, 1135,    0,    0,    0,    0,    0, 1145,
      262,    0,    0,    0,    0,    0,    0,    0, 1333, 1161,
     1164, 1168, 1172, 1176, 1180, 1184, 1188, 1192, 1196, 1200,
     1204, 1208, 1212, 1216, 1220, 1224, 1228, 1232, 1236, 1240,
     1244, 1248, 1252, 1256, 1260, 1264, 1268, 1272, 1276, 1280,
     1284, 1288, 1292, 1296, 1300, 1304, 1308, 1312, 1316, 1320,
     1324, 1328
    } ;

static const flex_int16_t yy_def[283] =
    {   0,
      239,    1,  239,  239,  240,  240,  239,    4,  241,    4,
      241,   11,    4,  239,   11,    4,  240,    7,   11,   13,
      240,    7,  242,  239,  243,    7,  239,  239,  243,  241,
       11,   11,   11,   11,    4,   14,  244,  239,  245,  246,
        4,  239,  247,  242,   24,   24,  248,   24,  248,  243,
        7,   27,  249,  239,  250,    4,  251,   28,  252,  239,
      253,  254,    4,   11,  255,  244,  240,   38,  239,  239,
      256,  257,    7,  256,  245,   11,   14,   42,   24,  258,
       42,  258,  247,   49,   49,   24,   24,   29,   42,  259,
      240,  249,   54,  239,  239,  260,    7,  261,  260,   11,

      250,   27,  262,  252,  240,   60,  239,  239,  263,  264,
        7,  263,  253,   11,   28,  255,  239,  239,  265,  266,
      267,   70,   70,  268,  269,   24,  268,  256,   29,  239,
       75,   49,  258,   42,   49,   49,  258,  239,  259,  239,
      270,  267,  271,   95,   95,  272,   24,  273,  272,   29,
      260,  239,  101,  262,  239,  239,  274,  275,  142,  108,
      108,  276,  277,   24,  276,  263,   29,  239,  113,  118,
       70,  278,  118,   42,  278,  265,  279,  127,  127,   49,
       70,   70,  128,  118,  140,   95,  280,   42,  140,  280,
      279,  270,  149,   49,  149,   95,   95,  151,  140,  156,

      108,  281,  156,   42,  281,  274,  279,  165,  165,   49,
      108,  108,  166,  156,  127,  175,  282,  118,  127,  127,
      175,  149,  282,  190,  140,  149,  149,  190,  165,  205,
      282,  156,  165,  165,  205,  175,  190,  205,    0,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239
    } ;

static const flex_int16_t yy_nxt[1350] =
    {   0,
        4,    5,    6,    7,    8,    9,    4,    4,   10,   11,
       12,   13,   14,    4,   15,    4,   16,   17,   17,   18,
       16,   19,   16,   16,   16,   19,   19,   20,   16,   16,
       19,   16,   22,   23,   23,   24,   22,   25,   22,   22,
       22,   25,   25,   26,   22,   22,   25,   22,   27,   29,
      239,   33,   37,   82,   53,   28,   34,   30,   29,   59,
       32,   83,   77,   69,  102,  239,   30,  239,   16,  115,
       16,  116,  117,  130,   16,   16,   35,  239,  239,   16,
       36,   37,   37,   38,   36,   39,   36,   36,   36,   39,
       39,   40,   41,   36,   39,   36,  239,  132,  132,   17,

      239,  239,   94,   17,   17,  133,  133,   58,   17,   42,
      138,   43,  152,   19,  139,   43,   43,   44,   21,  239,
       43,   45,   23,   23,   46,   45,   47,   45,   45,   45,
       47,   47,   48,   45,   45,   47,   45,   43,   43,   49,
      154,   52,  107,   19,  155,  132,  132,   50,  239,   22,
       82,   22,  168,  133,  133,   22,   22,   51,   83,  239,
       22,   52,   53,   53,   54,   52,   55,   52,   56,   52,
       55,   55,   57,   52,   52,   55,   52,   58,   59,   59,
       60,   58,   61,   58,   58,   58,   61,   61,   62,   58,
       58,   61,   63,   43,   43,   49,   21,   82,   82,  132,

      137,  239,   36,   50,   65,   83,   83,  133,   65,   65,
       66,   67,   19,   65,   68,   69,   69,   70,   68,   71,
       68,   68,   68,   71,   71,   72,   73,   68,   71,   68,
       65,   65,   74,   21,  239,   19,   89,  239,   16,   64,
       75,   76,   78,   17,   17,   79,   78,   80,   78,   78,
       78,   80,   80,   81,   78,   78,   80,   78,   43,   43,
       84,   19,   19,  132,   19,  132,   30,   19,   85,  239,
       86,  133,   45,  133,   21,   19,   45,   45,   87,   31,
       21,   45,   43,   43,   84,   21,  239,  239,  239,  239,
      239,  239,   85,   43,  239,  239,  239,  239,  239,  239,

      239,  239,  239,   88,   90,  239,   91,  239,   90,   90,
       92,  239,  239,   90,   93,   94,   94,   95,   93,   96,
       93,   97,   93,   96,   96,   98,   93,   93,   96,   93,
       90,   90,   99,  239,  239,  239,  100,  239,  239,  239,
      101,  103,  239,  239,  239,  103,  103,  104,  239,  239,
      103,  105,  106,  107,  107,  108,  106,  109,  106,  106,
      106,  109,  109,  110,  106,  106,  109,  111,  103,  103,
      112,  239,  239,  239,  239,  239,  239,  239,  113,  239,
      239,  239,  114,   69,   69,   69,  118,   69,  119,   69,
       69,   69,  119,  119,  120,  121,   69,  119,   69,  122,

       69,   69,  123,  122,  124,  122,  122,  122,  124,  124,
      125,  126,  122,  124,  122,  119,  119,  127,  239,  239,
      239,  239,  239,  239,  239,  128,  129,  119,  119,  127,
      239,  239,  239,  239,  239,  239,  239,  128,  129,   65,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  131,
      239,  239,  239,   78,  239,  239,  239,   78,   78,  134,
      239,  239,   78,  239,  135,  239,  239,  239,  239,  239,
      239,  239,  136,   94,   94,   94,  140,   94,  141,   94,
      142,   94,  141,  141,  143,   94,   94,  141,   94,  144,
       94,   94,  145,  144,  146,  144,  147,  144,  146,  146,

      148,  144,  144,  146,  144,  141,  141,  149,  239,  239,
      239,  150,  239,  239,  239,  151,  141,  141,  149,  239,
      239,  239,  150,  239,  239,  239,  151,   90,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  153,  107,  107,
      107,  156,  107,  157,  107,  107,  107,  157,  157,  158,
      107,  107,  157,  159,  160,  107,  107,  161,  160,  162,
      160,  160,  160,  162,  162,  163,  160,  160,  162,  164,
      157,  157,  165,  239,  239,  239,  239,  239,  239,  239,
      166,  239,  239,  239,  167,  157,  157,  165,  239,  239,
      239,  239,  239,  239,  239,  166,  239,  239,  239,  167,

      103,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      169,  170,   37,   37,  171,  170,  172,  170,  170,  170,
      172,  172,  173,  174,  170,  172,  170,  175,  239,  239,
      239,  239,  239,  239,  239,  176,  177,   42,  239,   43,
      239,  239,  239,   43,   43,   44,  239,  239,   43,  119,
      119,  178,  239,  239,  239,  239,  239,  239,  239,  179,
      180,   69,  239,  181,  239,  239,  239,  239,  239,  239,
      239,  182,  119,  119,  178,  239,  239,  239,  239,  239,
      239,  239,  179,  180,  119,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  183,   68,   69,   69,  184,   68,

       71,   68,   68,   68,   71,   71,   72,   73,   68,   71,
       68,   65,  239,  239,  239,  239,  239,  239,  239,  239,
       75,   76,  185,   53,   53,  186,  185,  187,  185,  188,
      185,  187,  187,  189,  185,  185,  187,  185,  190,  239,
      239,  239,  191,  239,  239,  239,  192,   42,  239,   43,
      239,  239,  239,   43,   43,   44,  239,  239,   43,  141,
      141,  193,  239,  239,  239,  194,  239,  239,  239,  195,
       94,  239,  196,  239,  239,  239,  239,  239,  239,  239,
      197,  141,  141,  193,  239,  239,  239,  194,  239,  239,
      239,  195,  141,  239,  239,  239,  239,  239,  239,  239,

      239,  239,  198,   93,   94,   94,  199,   93,   96,   93,
       97,   93,   96,   96,   98,   93,   93,   96,   93,   90,
      239,  239,  239,  239,  100,  239,  239,  239,  101,  200,
       59,   59,  201,  200,  202,  200,  200,  200,  202,  202,
      203,  200,  200,  202,  204,  205,  239,  239,  239,  239,
      239,  239,  239,  206,  239,  239,  239,  207,  157,  157,
      208,  239,  239,  239,  239,  239,  239,  239,  209,  239,
      239,  239,  210,  107,  239,  211,  239,  239,  239,  239,
      239,  239,  239,  212,  157,  157,  208,  239,  239,  239,
      239,  239,  239,  239,  209,  239,  239,  239,  210,  157,

      239,  239,  239,  239,  239,  239,  239,  239,  239,  213,
      106,  107,  107,  214,  106,  109,  106,  106,  106,  109,
      109,  110,  106,  106,  109,  111,  103,  239,  239,  239,
      239,  239,  239,  239,  239,  113,  239,  239,  239,  114,
       65,   65,  215,  239,  239,  239,  239,  239,  239,  239,
      216,  217,  239,  239,  239,  170,  239,  239,  239,  170,
      170,  218,  170,  239,  170,   65,   65,  215,  239,  239,
      239,  239,  239,  239,  239,  216,  217,  239,  219,  239,
      239,  239,  239,  239,  239,  239,  220,  124,  119,  221,
      239,  239,  239,  239,  239,  239,  239,  128,  129,   90,

       90,  222,  239,  239,  239,  223,  239,  239,  239,  224,
      239,  239,  239,  185,  239,  185,  239,  185,  185,  225,
      239,  239,  185,   90,   90,  222,  239,  239,  239,  223,
      239,  239,  239,  224,  239,  226,  239,  239,  239,  146,
      239,  239,  239,  227,  141,  228,  239,  239,  239,  150,
      239,  239,  239,  151,  103,  103,  229,  239,  239,  239,
      239,  239,  239,  239,  230,  239,  239,  239,  231,  239,
      239,  239,  200,  239,  239,  239,  200,  200,  232,  239,
      239,  200,  200,  103,  103,  229,  239,  239,  239,  239,
      239,  239,  239,  230,  239,  239,  239,  231,  239,  233,

      239,  239,  239,  239,  239,  239,  239,  234,  239,  239,
      239,  162,  157,  235,  239,  239,  239,  239,  239,  239,
      239,  166,  239,  239,  239,  167,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  236,  172,  239,  239,  239,
      239,  239,  187,  239,  239,  239,  237,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  238,  239,  239,  239,
      202,   17,   17,   17,   19,  239,  239,   19,   23,   23,
       23,   23,   25,   25,   25,   25,   37,   37,   37,   37,
       39,   39,   39,   39,   36,   36,  239,   36,   43,   43,
       43,   43,   47,   47,   47,   47,   53,   53,   53,   53,

       55,   55,   55,   55,   52,   52,  239,   52,   59,   59,
       59,   59,   61,   61,   61,   61,   58,   58,  239,   58,
       65,   65,   65,   65,   71,   71,   71,   71,   68,   68,
      239,   68,   80,  239,  239,   80,   90,   90,   90,   90,
       96,   96,   96,   96,   93,   93,  239,   93,  103,  103,
      103,  103,  109,  109,  109,  109,  106,  106,  239,  106,
      119,  119,  119,  119,   69,   69,  239,   69,   23,   23,
       23,   23,  124,  124,  124,  124,  122,  122,  239,  122,
      141,  141,  141,  141,   94,   94,  239,   94,  146,  146,
      146,  146,  144,  144,  239,  144,  157,  157,  157,  157,

      107,  107,  239,  107,  162,  162,  162,  162,  160,  160,
      239,  160,  172,  172,  172,  172,   43,   43,   43,   43,
      187,  187,  187,  187,  202,  202,  202,  202,   80,  239,
      239,   80,    3,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239
    } ;

static const flex_int16_t yy_chk[1350] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    8,    9,
      206,   12,   40,   43,   57,    8,   12,    9,   11,   62,
       11,   43,   40,   72,   57,  192,   11,   13,   13,   62,
       13,   65,   65,   72,   13,   13,   13,  176,  154,   13,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   21,   80,   82,   21,

      139,  116,   98,   21,   21,   80,   82,  115,   21,   23,
       90,   23,   98,  114,   90,   23,   23,   23,  105,  104,
       23,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   25,   25,   25,
      103,  102,  110,  100,  103,  133,  137,   25,   26,   26,
      177,   26,  110,  133,  137,   26,   26,   26,  177,   92,
       26,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   29,   29,   29,   91,  191,  207,  217,

       88,   83,   77,   29,   37,  191,  207,  217,   37,   37,
       37,   37,   76,   37,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       39,   39,   39,   67,   66,   64,   51,   44,   35,   34,
       39,   39,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   47,   47,
       47,   33,   32,  223,   31,  231,   30,   19,   47,   48,
       48,  223,   48,  231,   17,   15,   48,   48,   48,   10,
        6,   48,   49,   49,   49,    5,    3,    0,    0,    0,
        0,    0,   49,   50,   50,    0,    0,    0,    0,    0,

        0,    0,    0,   50,   53,    0,   53,    0,   53,   53,
       53,    0,    0,   53,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       55,   55,   55,    0,    0,    0,   55,    0,    0,    0,
       55,   59,    0,    0,    0,   59,   59,   59,    0,    0,
       59,   59,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   61,   61,
       61,    0,    0,    0,    0,    0,    0,    0,   61,    0,
        0,    0,   61,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   70,

       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   71,   71,   71,    0,    0,
        0,    0,    0,    0,    0,   71,   71,   74,   74,   74,
        0,    0,    0,    0,    0,    0,    0,   74,   74,   75,
       75,    0,    0,    0,    0,    0,    0,    0,    0,   75,
       81,    0,    0,   81,    0,    0,    0,   81,   81,   81,
        0,    0,   81,   85,   85,    0,    0,    0,    0,    0,
        0,    0,   85,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,

       95,   95,   95,   95,   95,   96,   96,   96,    0,    0,
        0,   96,    0,    0,    0,   96,   99,   99,   99,    0,
        0,    0,   99,    0,    0,    0,   99,  101,  101,    0,
        0,    0,    0,    0,    0,    0,    0,  101,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      109,  109,  109,    0,    0,    0,    0,    0,    0,    0,
      109,    0,    0,    0,  109,  112,  112,  112,    0,    0,
        0,    0,    0,    0,    0,  112,    0,    0,    0,  112,

      113,  113,    0,    0,    0,    0,    0,    0,    0,    0,
      113,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  119,    0,    0,
        0,    0,    0,    0,    0,  119,  119,  121,    0,  121,
        0,    0,    0,  121,  121,  121,    0,    0,  121,  124,
      124,  124,    0,    0,    0,    0,    0,    0,    0,  124,
      124,  125,    0,  125,    0,    0,    0,    0,    0,    0,
        0,  125,  127,  127,  127,    0,    0,    0,    0,    0,
        0,    0,  127,  127,  128,  128,    0,    0,    0,    0,
        0,    0,    0,    0,  128,  130,  130,  130,  130,  130,

      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  131,    0,    0,    0,    0,    0,    0,    0,    0,
      131,  131,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  141,    0,
        0,    0,  141,    0,    0,    0,  141,  142,    0,  142,
        0,    0,    0,  142,  142,  142,    0,    0,  142,  146,
      146,  146,    0,    0,    0,  146,    0,    0,    0,  146,
      148,    0,  148,    0,    0,    0,    0,    0,    0,    0,
      148,  149,  149,  149,    0,    0,    0,  149,    0,    0,
        0,  149,  151,  151,    0,    0,    0,    0,    0,    0,

        0,    0,  151,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  153,
        0,    0,    0,    0,  153,    0,    0,    0,  153,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  157,    0,    0,    0,    0,
        0,    0,    0,  157,    0,    0,    0,  157,  162,  162,
      162,    0,    0,    0,    0,    0,    0,    0,  162,    0,
        0,    0,  162,  163,    0,  163,    0,    0,    0,    0,
        0,    0,    0,  163,  165,  165,  165,    0,    0,    0,
        0,    0,    0,    0,  165,    0,    0,    0,  165,  166,

      166,    0,    0,    0,    0,    0,    0,    0,    0,  166,
      168,  168,  168,  168,  168,  168,  168,  168,  168,  168,
      168,  168,  168,  168,  168,  168,  169,    0,    0,    0,
        0,    0,    0,    0,    0,  169,    0,    0,    0,  169,
      172,  172,  172,    0,    0,    0,    0,    0,    0,    0,
      172,  172,  173,    0,    0,  173,    0,    0,    0,  173,
      173,  173,  173,    0,  173,  175,  175,  175,    0,    0,
        0,    0,    0,    0,    0,  175,  175,  179,  179,    0,
        0,    0,    0,    0,    0,    0,  179,  179,  183,  183,
        0,    0,    0,    0,    0,    0,    0,  183,  183,  187,

      187,  187,    0,    0,    0,  187,    0,    0,    0,  187,
      189,    0,    0,  189,    0,  189,    0,  189,  189,  189,
        0,    0,  189,  190,  190,  190,    0,    0,    0,  190,
        0,    0,    0,  190,  195,  195,    0,    0,    0,  195,
        0,    0,    0,  195,  198,  198,    0,    0,    0,  198,
        0,    0,    0,  198,  202,  202,  202,    0,    0,    0,
        0,    0,    0,    0,  202,    0,    0,    0,  202,  203,
        0,    0,  203,    0,    0,    0,  203,  203,  203,    0,
        0,  203,  203,  205,  205,  205,    0,    0,    0,    0,
        0,    0,    0,  205,    0,    0,    0,  205,  209,  209,

        0,    0,    0,    0,    0,    0,    0,  209,    0,    0,
        0,  209,  213,  213,    0,    0,    0,    0,    0,    0,
        0,  213,    0,    0,    0,  213,  216,    0,    0,    0,
        0,    0,    0,    0,    0,  216,  216,  224,    0,    0,
        0,    0,  224,    0,    0,    0,  224,  230,    0,    0,
        0,    0,    0,    0,    0,    0,  230,    0,    0,    0,
      230,  240,  240,  240,  241,    0,    0,  241,  242,  242,
      242,  242,  243,  243,  243,  243,  244,  244,  244,  244,
      245,  245,  245,  245,  246,  246,    0,  246,  247,  247,
      247,  247,  248,  248,  248,  248,  249,  249,  249,  249,

      250,  250,  250,  250,  251,  251,    0,  251,  252,  252,
      252,  252,  253,  253,  253,  253,  254,  254,    0,  254,
      255,  255,  255,  255,  256,  256,  256,  256,  257,  257,
        0,  257,  258,    0,    0,  258,  259,  259,  259,  259,
      260,  260,  260,  260,  261,  261,    0,  261,  262,  262,
      262,  262,  263,  263,  263,  263,  264,  264,    0,  264,
      265,  265,  265,  265,  266,  266,    0,  266,  267,  267,
      267,  267,  268,  268,  268,  268,  269,  269,    0,  269,
      270,  270,  270,  270,  271,  271,    0,  271,  272,  272,
      272,  272,  273,  273,    0,  273,  274,  274,  274,  274,

      275,  275,    0,  275,  276,  276,  276,  276,  277,  277,
        0,  277,  278,  278,  278,  278,  279,  279,  279,  279,
      280,  280,  280,  280,  281,  281,  281,  281,  282,    0,
        0,  282,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[18] =
    {   0,
1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "shell.l"
/*
 *
 * CS-252 
 * shell.l: lexical analyzer for shell
 * You have to extend it.
 *
 */
#line 11 "shell.l"

#include <cstring>
#include <unistd.h>
#include <sys/types.h> 
#include <sys/wait.h> 
#include <iostream>
#include <limits.h>
#include <stdlib.h>
#include <math.h>
#include "y.tab.hh"
#include "shell.hh"

using namespace std;

///////////////////////// Start of Edit Mode Code /////////////////////////

extern "C" char * read_line();

int mygetc(FILE * f) {
  static char *p;
  char ch;

     if (!isatty(0)) {
  // stdin is not a tty. Call real getc
    return getc(f);
  }

  // stdin is a tty. Call our read_line.
  if (p==NULL || *p == 0) {
    char * s = read_line();
    p = s;
  }

  ch = *p;
  p++;

  return ch;
}

#undef getc
#define getc(f) mygetc(f)

///////////////////////// End of Edit Mode Code /////////////////////////

static  void yyunput (int c,char *buf_ptr  );

void myunputc(int c) {
  unput(c);
}

void initBfr() {
  yypush_buffer_state(yy_create_buffer(stdin, YY_BUF_SIZE));
}

void termBfr() {
  while ( YY_CURRENT_BUFFER ) {
    YY_FLUSH_BUFFER;
    yypop_buffer_state();
  }
}

void flushBfr() { YY_FLUSH_BUFFER; }

void swtchBfr(char * input) {
  yy_switch_to_buffer(yy_scan_string(input));
}

void source(char * file) {
  FILE * fp;
  if (!(fp = fopen(file, "r"))) {
    perror("IO");
    return;
  }
  yypush_buffer_state(yy_create_buffer(fp, YY_BUF_SIZE));
}

std::string * removeE(char * s) {
  std::string* str = new std::string();
  for(int i = 0; i < strlen(s); i++) {
    if ((i > 0 && s[i - 1] == '\\') || (s[i] != '\"' && s[i] != '\\')) {
      str->push_back(s[i]);
      //printf("%c", s[i]);
    }
  }
  return str;
}

void unputStr(char * input) {
  int i = 0;
  while(input[i] != '\0') {
    if (input[i] == '\n') input[i] = ' ';
    //printf("%c", input[i]);
    i++;
  }
  if (i == 0) printf("shell: subshell execution error\n");
  else {
    for (i = i - 1; i >= 0; i--) {
    //printf("%c", input[i]);
    myunputc(input[i]);
    }
  }
}

char * envExp(char * input) {
  char * env;
  if (!strcmp(input, "$")) {
    pid_t pid = getpid();
    int lengthD = pid == 0 ? 1 : floor(log10(abs(pid))) + 1;
    char * output = (char*)calloc(lengthD + 1, sizeof(char));
    sprintf(output, "%d", pid);
    return output;
  }
  if (!strcmp(input, "?")) {
    int lengthD = Shell::lstRtn == 0 ? 1 : floor(log10(abs(Shell::lstRtn))) + 1;
    char * output = (char*)calloc(lengthD + 1, sizeof(char));
    sprintf(output, "%d", Shell::lstRtn);
    return output;
  }
  if (!strcmp(input, "!")) {
    int lengthD = Shell::lstPid == 0 ? 1 : floor(log10(abs(Shell::lstPid))) + 1;
    char * output = (char*)calloc(lengthD + 1, sizeof(char));
    sprintf(output, "%d", Shell::lstPid);
    return output;
  }
  if (!strcmp(input, "_")) {
    if (Shell::lstArg != NULL) {
      char * output = (char*)calloc(strlen(Shell::lstArg) + 1, sizeof(char));
      strcpy(output, Shell::lstArg);
      return output;
    } else return (char*)calloc(1, sizeof(char));
  }
  if (!strcmp(input, "SHELL")) {
    return realpath(Shell::argv, NULL);
  }
  if ((env = getenv(input)) != NULL) {
    char * output = (char*)calloc(strlen(env) + 1, sizeof(char));
    strcpy(output, env);
    return output;
  } else return (char *)calloc(1, sizeof(char));
}

char * subshell (char ** input) {
  //printf("subshell function call: %s\n", input[0]);
  int size = 8;
  char* out = (char*)malloc(size);
  int p[2];
  if ( pipe(p) == -1) {
    perror( "shell: pipe");
    exit( 2 );
  }
  int pid = fork();
  if ( pid == -1 ) {
    perror( "shell: fork");
    exit( 2 );
  }

  if (pid == 0) {
    //printf("input: %s\n", input[0]);
    dup2(p[1], 1);
    close(p[0]);
    close(p[1]);
    execvp("/proc/self/exe", input);
    perror("child");
  }
  close(p[1]);
  waitpid(pid, 0, 0);

  int i, c;
  i = 0;
  FILE* file = fdopen (p[0], "r");
  while ((c = fgetc (file)) != EOF) {
    if (i == size - 1) {
      size *= 2;
      out = (char*)realloc(out, size);
    }
    out[i++] = c;
    //putchar(c);
  }
  out[i] = 0;

  //printf("size: %d\n", size);
  //printf("str: %s\n", out);
  
  fclose(file);
  close(p[0]);
  
  //printf("print ended\n");
  return out;
}


#line 1053 "lex.yy.cc"
#line 1054 "lex.yy.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 206 "shell.l"


#line 1274 "lex.yy.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 240 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1333 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 208 "shell.l"
{
  return NEWLINE;
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 212 "shell.l"
{
  yylval.cpp_string = removeE(yytext);
  return WORD;
}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 217 "shell.l"
{
  char ** word = (char**) malloc(3);
  word[2] = 0;
  word[1] = (char *)malloc(strlen(yytext) - 2);
  memcpy(word[1], yytext + 2, strlen(yytext) - 3);
  word[1][strlen(yytext) - 3] = '\0';
  word[0] = (char *)malloc(6);
  strcpy(*word, "shell\0");
  char * out = subshell(word);
  free(*word);
  free(word[1]);
  free(word);

  unputStr(out);
  free(out);
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 234 "shell.l"
{
  char ** word = (char**) malloc(3);
  word[2] = 0;
  word[1] = (char *)malloc(strlen(yytext) - 1);
  memcpy(word[1], yytext + 1, strlen(yytext) - 2);
  word[1][strlen(yytext) - 2] = '\0';
  word[0] = (char *)malloc(6);
  strcpy(*word, "shell\0");
  //printf("yytext: %s\n", yytext);

  char * out = subshell(word);
  free(*word);
  free(word[1]);
  free(word);

  unputStr(out);
  free(out);
}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 253 "shell.l"
{
  char * word = (char *)calloc(strlen(yytext) - 2, sizeof(char));
  memcpy(word, yytext + 2, strlen(yytext) - 3);
  //printf("input: %s\n", word);
  char * out = envExp(word);
  //printf("output: %s\n", out);
  yylval.cpp_string = new std::string(out);
  free(out);
  free(word);

  return WORD;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 266 "shell.l"
{
  /* Discard spaces and tabs */
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 270 "shell.l"
{
  return GUARD;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 274 "shell.l"
{
  return GREAT2;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 278 "shell.l"
{
  return GGCONT;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 282 "shell.l"
{
  return GCONT;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 286 "shell.l"
{
  return LCONT;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 290 "shell.l"
{
  return GGREAT;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 294 "shell.l"
{
  return GREAT;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 298 "shell.l"
{
  return LESS;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 302 "shell.l"
{
  return CONT;
}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 306 "shell.l"
{
  /* Assume that file names have only alpha chars */
  yylval.cpp_string = removeE(yytext);

  //printf("lex scanned: %s\n", yytext);
  //cout << *yylval.cpp_string << endl;
  return WORD;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 315 "shell.l"
{
  //printf("EOF\n");
  YY_FLUSH_BUFFER;
  yypop_buffer_state();
  if ( !YY_CURRENT_BUFFER ) {
    Shell::_currentCommand.execute();
    yyterminate();
  }
  return NEWLINE;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 326 "shell.l"
ECHO;
	YY_BREAK
#line 1520 "lex.yy.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 240 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 240 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 239);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 326 "shell.l"


